import type { SupportedLanguage } from "./i18n";

type AuthCopy = {
  tagline: string; splashCaption: string; abdmReady: string; heroEyebrow: string; heroTitleA: string; heroTitleB: string; heroDescription: string;
  careContinuity: string; offlineFirst: string; builtForVillage: string; secureAccess: string; encrypted: string;
  welcome: string; connectedTitle: string; connectedDescription: string; selectUserType: string; worker: string; doctor: string; user: string;
  phoneNumber: string; aadhaarNumber: string; secureMock: string; sendCode: string; demoDashboard: string; abdmAligned: string; offlineReady: string; privacy: string; help: string;
  checkMessages: string; otpTitleA: string; otpTitleB: string; otpDescription: string; verificationCode: string; demoCode: string; resend: string; verify: string; differentNumber: string; prototype: string; useCode: string;
};

const copies: Record<SupportedLanguage, AuthCopy> = {
  English: {
    tagline: "care, connected", splashCaption: "A more connected way to care.", abdmReady: "ABDM-ready care coordination", heroEyebrow: "Rural care, reimagined", heroTitleA: "Good care should", heroTitleB: "travel further.", heroDescription: "One calm, connected workspace for community health workers and specialists.", careContinuity: "care continuity", offlineFirst: "Offline-first", builtForVillage: "built for every village", secureAccess: "Secure access", encrypted: "encrypted", welcome: "Welcome back", connectedTitle: "Let’s get you connected.", connectedDescription: "Use your phone number or Aadhaar to securely access your care workspace.", selectUserType: "Select user type", worker: "Worker", doctor: "Doctor", user: "User", phoneNumber: "Phone number", aadhaarNumber: "Aadhaar number", secureMock: "This is a secure mock verification for the prototype.", sendCode: "Send verification code", demoDashboard: "Explore a sample dashboard", abdmAligned: "ABDM aligned", offlineReady: "Offline-ready", privacy: "Privacy", help: "Help", checkMessages: "Check your messages", otpTitleA: "Enter your", otpTitleB: "one-time code.", otpDescription: "We sent a 6-digit verification code to your registered number ending in", verificationCode: "Verification code", demoCode: "Demo code", resend: "Resend code", verify: "Verify & continue", differentNumber: "← Use a different number", prototype: "Prototype mode", useCode: "use 123456 to continue."
  },
  "हिंदी": {
    tagline: "देखभाल, साथ-साथ", splashCaption: "देखभाल का एक और जुड़ा हुआ तरीका।", abdmReady: "ABDM-तैयार स्वास्थ्य समन्वय", heroEyebrow: "ग्रामीण स्वास्थ्य सेवा, नए रूप में", heroTitleA: "अच्छी देखभाल", heroTitleB: "दूर तक पहुँचनी चाहिए।", heroDescription: "सामुदायिक स्वास्थ्य कार्यकर्ताओं और विशेषज्ञों के लिए एक शांत, जुड़ा हुआ कार्यक्षेत्र।", careContinuity: "देखभाल की निरंतरता", offlineFirst: "ऑफ़लाइन-प्रथम", builtForVillage: "हर गाँव के लिए बनाया गया", secureAccess: "सुरक्षित प्रवेश", encrypted: "एन्क्रिप्टेड", welcome: "वापसी पर स्वागत है", connectedTitle: "आइए आपको जोड़ते हैं।", connectedDescription: "अपने स्वास्थ्य कार्यक्षेत्र में सुरक्षित रूप से प्रवेश करने के लिए फ़ोन नंबर या आधार का उपयोग करें।", selectUserType: "उपयोगकर्ता प्रकार चुनें", worker: "कार्यकर्ता", doctor: "डॉक्टर", user: "उपयोगकर्ता", phoneNumber: "फ़ोन नंबर", aadhaarNumber: "आधार नंबर", secureMock: "यह प्रोटोटाइप के लिए सुरक्षित मॉक सत्यापन है।", sendCode: "सत्यापन कोड भेजें", demoDashboard: "सैंपल डैशबोर्ड देखें", abdmAligned: "ABDM अनुरूप", offlineReady: "ऑफ़लाइन तैयार", privacy: "गोपनीयता", help: "मदद", checkMessages: "अपने संदेश देखें", otpTitleA: "अपना", otpTitleB: "वन-टाइम कोड दर्ज करें।", otpDescription: "हमने आपके पंजीकृत नंबर के अंत में दिए गए", verificationCode: "सत्यापन कोड", demoCode: "डेमो कोड", resend: "कोड फिर भेजें", verify: "सत्यापित करें और जारी रखें", differentNumber: "← अलग नंबर का उपयोग करें", prototype: "प्रोटोटाइप मोड", useCode: "जारी रखने के लिए 123456 उपयोग करें।"
  },
  "मराठी": {
    tagline: "काळजी, जोडलेली", splashCaption: "काळजी घेण्याचा अधिक जोडलेला मार्ग.", abdmReady: "ABDM-सज्ज आरोग्य समन्वय", heroEyebrow: "ग्रामीण आरोग्यसेवेचा नवा विचार", heroTitleA: "चांगली काळजी", heroTitleB: "दूरवर पोहोचली पाहिजे.", heroDescription: "समुदाय आरोग्य कार्यकर्ते आणि तज्ज्ञांसाठी एक शांत, जोडलेले कार्यक्षेत्र.", careContinuity: "काळजीची सातत्यता", offlineFirst: "ऑफलाइन-प्रथम", builtForVillage: "प्रत्येक गावासाठी तयार", secureAccess: "सुरक्षित प्रवेश", encrypted: "एन्क्रिप्टेड", welcome: "पुन्हा स्वागत आहे", connectedTitle: "चला, तुम्हाला जोडूया.", connectedDescription: "तुमच्या आरोग्य कार्यक्षेत्रात सुरक्षितपणे प्रवेश करण्यासाठी फोन नंबर किंवा आधार वापरा.", selectUserType: "वापरकर्ता प्रकार निवडा", worker: "कार्यकर्ता", doctor: "डॉक्टर", user: "वापरकर्ता", phoneNumber: "फोन नंबर", aadhaarNumber: "आधार नंबर", secureMock: "हे प्रोटोटाइपसाठी सुरक्षित मॉक पडताळणी आहे.", sendCode: "पडताळणी कोड पाठवा", demoDashboard: "नमुना डॅशबोर्ड पहा", abdmAligned: "ABDM अनुरूप", offlineReady: "ऑफलाइन-सज्ज", privacy: "गोपनीयता", help: "मदत", checkMessages: "तुमचे संदेश तपासा", otpTitleA: "तुमचा", otpTitleB: "वन-टाइम कोड प्रविष्ट करा.", otpDescription: "तुमच्या नोंदणीकृत क्रमांकाच्या शेवटी", verificationCode: "पडताळणी कोड", demoCode: "डेमो कोड", resend: "कोड पुन्हा पाठवा", verify: "पडताळा आणि पुढे जा", differentNumber: "← वेगळा नंबर वापरा", prototype: "प्रोटोटाइप मोड", useCode: "पुढे जाण्यासाठी 123456 वापरा."
  }
};
export const getAuthCopy = (language: SupportedLanguage) => copies[language];

export const getSuccessCopy = (language: SupportedLanguage) => ({
  English: { verified: "Identity verified", readyA: "Your ABHA ID is", readyB: "ready.", signedIn: "Your account has been created and you’re being signed in automatically.", abhaLabel: "Your ABHA ID" },
  "हिंदी": { verified: "पहचान सत्यापित", readyA: "आपकी ABHA ID", readyB: "तैयार है।", signedIn: "आपका खाता बन गया है और आपको स्वचालित रूप से साइन इन किया जा रहा है।", abhaLabel: "आपकी ABHA ID" },
  "मराठी": { verified: "ओळख पडताळली", readyA: "तुमचा ABHA ID", readyB: "तयार आहे.", signedIn: "तुमचे खाते तयार झाले आहे आणि तुम्हाला आपोआप साइन इन केले जात आहे.", abhaLabel: "तुमचा ABHA ID" }
}[language]);
