import type { SupportedLanguage } from "./i18n";

type WorkerCopy = {
  todayWork: string; highRisk: string; followUps: string; scheduledVisits: string; nextAction: string; highRiskPregnancy: string; bpElevated: string; followUpOverdue: string; lowHemoglobin: string; viewPatient: string; quickActions: string; quickAddPatient: string; searchPatient: string; voiceEntry: string; recordVitals: string; capturePhoto: string; homeVisit: string; createReferral: string; riskAlerts: string; todaysTasks: string; offlineMode: string; offlineReady: string; syncPending: string; pregnancy: string;
};
const copy: Record<SupportedLanguage, WorkerCopy> = {
  English: { todayWork: "Today’s work", highRisk: "High-risk cases", followUps: "Follow-ups", scheduledVisits: "Scheduled visits", nextAction: "Next best action", highRiskPregnancy: "High-risk pregnancy", bpElevated: "BP elevated", followUpOverdue: "Follow-up overdue", lowHemoglobin: "Low hemoglobin", viewPatient: "View patient", quickActions: "Field actions", quickAddPatient: "Quick add patient", searchPatient: "Patient search", voiceEntry: "Voice-first entry", recordVitals: "Record vitals", capturePhoto: "Photo / document", homeVisit: "Home visit recording", createReferral: "Create referral", riskAlerts: "Risk alerts", todaysTasks: "Today’s tasks", offlineMode: "Offline mode", offlineReady: "Ready to work offline", syncPending: "Changes sync when connected", pregnancy: "Pregnancy care" },
  "हिंदी": { todayWork: "आज का काम", highRisk: "उच्च जोखिम केस", followUps: "फॉलो-अप", scheduledVisits: "निर्धारित भेंट", nextAction: "अगला ज़रूरी कदम", highRiskPregnancy: "उच्च जोखिम गर्भावस्था", bpElevated: "BP बढ़ा हुआ", followUpOverdue: "फॉलो-अप बाकी", lowHemoglobin: "हीमोग्लोबिन कम", viewPatient: "मरीज़ देखें", quickActions: "फील्ड कार्य", quickAddPatient: "जल्दी मरीज़ जोड़ें", searchPatient: "मरीज़ खोजें", voiceEntry: "आवाज़ से जानकारी", recordVitals: "वाइटल दर्ज करें", capturePhoto: "फोटो / दस्तावेज़", homeVisit: "घर की भेंट रिकॉर्ड करें", createReferral: "रेफरल बनाएँ", riskAlerts: "जोखिम अलर्ट", todaysTasks: "आज के कार्य", offlineMode: "ऑफ़लाइन मोड", offlineReady: "ऑफ़लाइन काम के लिए तैयार", syncPending: "कनेक्ट होने पर बदलाव सिंक होंगे", pregnancy: "गर्भावस्था देखभाल" },
  "मराठी": { todayWork: "आजचे काम", highRisk: "उच्च जोखमीच्या केसेस", followUps: "फॉलो-अप", scheduledVisits: "नियोजित भेटी", nextAction: "पुढील महत्त्वाची कृती", highRiskPregnancy: "उच्च जोखमीची गर्भावस्था", bpElevated: "BP वाढलेला", followUpOverdue: "फॉलो-अप बाकी", lowHemoglobin: "हिमोग्लोबिन कमी", viewPatient: "रुग्ण पहा", quickActions: "फील्ड कृती", quickAddPatient: "त्वरित रुग्ण जोडा", searchPatient: "रुग्ण शोधा", voiceEntry: "आवाजातून नोंद", recordVitals: "वाइटल्स नोंदवा", capturePhoto: "फोटो / कागदपत्र", homeVisit: "घरची भेट नोंदवा", createReferral: "रेफरल तयार करा", riskAlerts: "जोखीम सूचना", todaysTasks: "आजची कामे", offlineMode: "ऑफलाइन मोड", offlineReady: "ऑफलाइन कामासाठी तयार", syncPending: "कनेक्ट झाल्यावर बदल सिंक होतील", pregnancy: "गर्भावस्था काळजी" }
};
export const getWorkerCopy = (language: SupportedLanguage) => copy[language];
